// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCorePropiedadprodSubcategoria = "core_propiedadprod_subcategorias"

// CorePropiedadprodSubcategoria mapped from table <core_propiedadprod_subcategorias>
type CorePropiedadprodSubcategoria struct {
	ID              int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PropiedadprodID int32 `gorm:"column:propiedadprod_id;not null" json:"propiedadprod_id"`
	SubcategoriaID  int32 `gorm:"column:subcategoria_id;not null" json:"subcategoria_id"`
}

// TableName CorePropiedadprodSubcategoria's table name
func (*CorePropiedadprodSubcategoria) TableName() string {
	return TableNameCorePropiedadprodSubcategoria
}
