// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCoreMarca = "core_marca"

// CoreMarca mapped from table <core_marca>
type CoreMarca struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Estado          bool      `gorm:"column:estado;not null" json:"estado"`
	Fechacreado     time.Time `gorm:"column:fechacreado;not null" json:"fechacreado"`
	Fechamodificado time.Time `gorm:"column:fechamodificado;not null" json:"fechamodificado"`
	Usuariocrea     string    `gorm:"column:usuariocrea" json:"usuariocrea"`
	Descripcion     string    `gorm:"column:descripcion;not null" json:"descripcion"`
}

// TableName CoreMarca's table name
func (*CoreMarca) TableName() string {
	return TableNameCoreMarca
}
