// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCorePropiedadprodvalor = "core_propiedadprodvalor"

// CorePropiedadprodvalor mapped from table <core_propiedadprodvalor>
type CorePropiedadprodvalor struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Estado          bool      `gorm:"column:estado;not null" json:"estado"`
	Fechacreado     time.Time `gorm:"column:fechacreado;not null" json:"fechacreado"`
	Fechamodificado time.Time `gorm:"column:fechamodificado;not null" json:"fechamodificado"`
	Usuariocrea     string    `gorm:"column:usuariocrea" json:"usuariocrea"`
	Valor           string    `gorm:"column:valor" json:"valor"`
	ValorDefecto    string    `gorm:"column:valor_defecto" json:"valor_defecto"`
	PropiedadID     int32     `gorm:"column:propiedad_id;not null" json:"propiedad_id"`
}

// TableName CorePropiedadprodvalor's table name
func (*CorePropiedadprodvalor) TableName() string {
	return TableNameCorePropiedadprodvalor
}
