// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCoreNomencladorproductoPropiedade = "core_nomencladorproducto_propiedades"

// CoreNomencladorproductoPropiedade mapped from table <core_nomencladorproducto_propiedades>
type CoreNomencladorproductoPropiedade struct {
	ID                    int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NomencladorproductoID int32 `gorm:"column:nomencladorproducto_id;not null" json:"nomencladorproducto_id"`
	PropiedadprodID       int32 `gorm:"column:propiedadprod_id;not null" json:"propiedadprod_id"`
}

// TableName CoreNomencladorproductoPropiedade's table name
func (*CoreNomencladorproductoPropiedade) TableName() string {
	return TableNameCoreNomencladorproductoPropiedade
}
