// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCoreProductom = "core_productom"

// CoreProductom mapped from table <core_productom>
type CoreProductom struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Estado          bool      `gorm:"column:estado;not null" json:"estado"`
	Fechacreado     time.Time `gorm:"column:fechacreado;not null" json:"fechacreado"`
	Fechamodificado time.Time `gorm:"column:fechamodificado;not null" json:"fechamodificado"`
	Usuariocrea     string    `gorm:"column:usuariocrea" json:"usuariocrea"`
	Imagen          string    `gorm:"column:imagen" json:"imagen"`
	Peso            float64   `gorm:"column:peso;not null" json:"peso"`
	PresentacionID  int32     `gorm:"column:presentacion_id" json:"presentacion_id"`
	ProductoID      int32     `gorm:"column:producto_id;not null" json:"producto_id"`
	SeccionID       int32     `gorm:"column:seccion_id" json:"seccion_id"`
	TipopesoID      int32     `gorm:"column:tipopeso_id" json:"tipopeso_id"`
}

// TableName CoreProductom's table name
func (*CoreProductom) TableName() string {
	return TableNameCoreProductom
}
