// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/nrfta/go-paging"
)

type CategoriaNode struct {
	Estado          bool               `json:"estado"`
	Fechacreado     string             `json:"fechacreado"`
	Fechamodificado string             `json:"fechamodificado"`
	ID              string             `json:"id"`
	CategoriaPadre  *CategoriaNode     `json:"categoriaPadre"`
	TipoCategoria   *TipoCategoriaNode `json:"tipoCategoria"`
	Descripcion     string             `json:"descripcion"`
	ImageDefault    string             `json:"imageDefault"`
	Descuento       int                `json:"descuento"`
	CodigoPais      *string            `json:"codigoPais"`
	CodigoLetra     *string            `json:"codigoLetra"`
}

type CategoriaNodeConnection struct {
	PageInfo *paging.PageInfo     `json:"pageInfo"`
	Edges    []*CategoriaNodeEdge `json:"edges"`
}

type CategoriaNodeEdge struct {
	Cursor string         `json:"cursor"`
	Node   *CategoriaNode `json:"node"`
}

type TipoCategoriaNode struct {
	Estado          bool    `json:"estado"`
	Fechacreado     string  `json:"fechacreado"`
	Fechamodificado string  `json:"fechamodificado"`
	ID              string  `json:"id"`
	Nombre          string  `json:"nombre"`
	Abrev           string  `json:"abrev"`
	Sub             *string `json:"sub"`
}

type User struct {
	ID                string                 `json:"id"`
	Name              string                 `json:"name"`
	FriendsConnection *UserFriendsConnection `json:"friendsConnection"`
}

type UserFriendsConnection struct {
	PageInfo *paging.PageInfo   `json:"pageInfo"`
	Edges    []*UserFriendsEdge `json:"edges"`
}

type UserFriendsEdge struct {
	Cursor string `json:"cursor"`
	Node   *User  `json:"node"`
}
